📝 docs: Fix typo in Wilson's Twitter link
base-org/op-viem pull request #97
Opened 2023-09-16 20:09 UTC by duckception

🫡

2023-09-16 20:13 UTC, wilsoncusack approved these changes

2023-09-16 20:46 UTC, wilsoncusack requested changes

2023-09-16 20:46 UTC, wilsoncusack commented on README.md
> +- Follow [@wilsoncuask](https://twitter.com/wilsoncusack) Twitter for project updates
err might want to fix both :) 
```suggestion
- Follow [@wilsoncusack](https://twitter.com/wilsoncusack) Twitter for project updates
```

2023-09-16 21:03 UTC, wilsoncusack submitted a review, later dismissed

2023-09-16 21:05 UTC, wilsoncusack commented
there was a flaky test you may need to rebase sry :/

2023-09-17 10:29 UTC, duckception commented
> there was a flaky test you may need to rebase sry :/

Done 🫡

2023-09-17 23:17 UTC, wilsoncusack commented on README.md
> +- Follow [@wilsoncuask](https://twitter.com/wilsoncusack) Twitter for project updates
@duckception looks like this got reverted?

2023-09-19 13:54 UTC, wilsoncusack commented on README.md
> +- Follow [@wilsoncuask](https://twitter.com/wilsoncusack) Twitter for project updates
```suggestion
- Follow [@wilsoncusack](https://twitter.com/wilsoncusack) Twitter for project updates
```

2023-09-19 15:20 UTC, merged